-- AlterTable
ALTER TABLE `admin` ADD COLUMN `role` ENUM('RECORDER', 'ADMIN', 'SUPER_ADMIN') NOT NULL DEFAULT 'ADMIN';

-- AlterTable
ALTER TABLE `recorder` ADD COLUMN `role` ENUM('RECORDER', 'ADMIN', 'SUPER_ADMIN') NOT NULL DEFAULT 'RECORDER';
